---

- name: Deploy PostgreSQL server
  become: true
  hosts: appdbs
  gather_facts: false
  roles:
    - {name: base-config, tags: base-config}
    - {name: db-tier, tags: [db-tier, dbs, PostgreSQL]}

- name: Deploy application servers
  become: true
  hosts: apps
  gather_facts: false
  roles:
    - {name: base-config, tags: base-config}
    - {name: app-tier, tags: [app-tier, apps, Tomcat]}

- name: Deploy load balancer servers
  become: true
  hosts: frontends
  gather_facts: false
  roles:
    - {name: base-config, tags: base-config}
    - {name: lb-tier, tags: [lb-tier, lbs, HAProxy]}
  tasks:
    - uri:
        url: "http://{{ inventory_hostname }}"
        return_content: yes
      register: webpage

    - name: Fail if the page content does not have 'Ansible has done its job'
      fail:
      when: "'Ansible has done its job' not in webpage.content"

...
