---
# tasks file for osp-securitygroup
  - os_security_group:
      cloud: "{{ cloud_name }}"
      state: present
      name: "{{ item.name }}"
      description: ports_open
    with_items:
      - "{{ osp_securitygroups }}"
  - os_security_group_rule:
      cloud: "{{ cloud_name }}"
      security_group: "{{ item.0.name }}"
      protocol: "{{ item.1.protocol }}"
      port_range_min: "{{ item.1.port_range_min }}"
      port_range_max: "{{ item.1.port_range_max }}"
      remote_ip_prefix: "{{ item.1.remote_ip_prefix }}"
    with_subelements:
      - "{{ osp_securitygroups }}"
      - rules
