---

- name: Create bin directory
  file:
    path: /root/bin
    state: directory
    mode: 0755
- name: copy common.sh script
  copy:
    src: common.sh
    dest: /root/bin/common.sh
    mode: 0755
- name: copy order_svc.sh script
  copy:
    src: order_svc.sh
    dest: /root/bin/order_svc.sh
    mode: 0755
- name: copy jq script
  copy:
    src: jq
    dest: /root/bin/jq
    mode: 0644
- name: copy credentials file
  template:
    src: credentials.j2
    dest: /root/credentials.rc
    mode: 0644
- name: Execute script to create AWS infrastructure for 3 Tier Application
  script: wrapper.sh
  args:
    chdir: /root/bin
    creates: /root/order_svc.log

...
